spring.application.name=backend
# SQL Server Connection Details
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=Money_saver;integratedSecurity=true;encrypt=true;trustServerCertificate=true;
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Hibernate/JPA Settings
# 'none' is crucial here! It tells Spring NOT to delete or overwrite the tables you already built in SSMS.
spring.jpa.hibernate.ddl-auto=none

# Show the SQL queries Spring runs in the console (great for debugging)
spring.jpa.show-sql=true

spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl